/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author HP
 */
import Singleton.VoyageList;
import VoyageModels.Voyage;
import UserModels.*;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JOptionPane;
public class AdminCheckVoyagesScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminCheckVoyagesScreen
     */
    private User currentUser;
    private JPanel jPanelVoyages;
    private VoyageList voyageList;
    
    public AdminCheckVoyagesScreen(User user) {
        initComponents();
        this.currentUser = user;
        setLocationRelativeTo(null);
        voyageList = VoyageList.getInstance();

        jPanelVoyages = new JPanel();
        jPanelVoyages.setLayout(new BoxLayout(jPanelVoyages, BoxLayout.Y_AXIS));

        // ScrollPane oluştur
        JScrollPane scrollPane = new JScrollPane(jPanelVoyages);
        scrollPane.setPreferredSize(new Dimension(580, 300));

        // Layout ayarları
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(jLabel6, BorderLayout.NORTH);
        getContentPane().add(jSeparator2, BorderLayout.AFTER_LAST_LINE);
        getContentPane().add(scrollPane, BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    for (Voyage voyage : voyageList) {
        // Her voyage için panel
            JPanel voyagePanel = new JPanel(new FlowLayout(FlowLayout.LEFT));

            // Sefer bilgisi label
            JLabel infoLabel = new JLabel(
                voyage.getOrigin() + " -> " + voyage.getDestination() +
                " | Date: " + voyage.getDate() +
                " | Time: " + voyage.getTime() +
                " | Code: " + voyage.getVoyageCode()
            );
            
            JButton deleteButton = new JButton("Delete Voyage");
            deleteButton.addActionListener(e -> {
                int result = JOptionPane.showConfirmDialog(this,
                "Are you sure to delete voyage: " + voyage.getVoyageCode() + "?",
                "Confirm",
                JOptionPane.YES_NO_OPTION
                );
                if (result == JOptionPane.YES_OPTION) {
                    voyageList.removeVoyage(voyage);
                    new AdminScreen(currentUser).setVisible(true);
                    this.dispose();
                }           
            });

            // Panel içine ekle
            voyagePanel.add(infoLabel);
            voyagePanel.add(deleteButton);

            // Ana panel listesine ekle
            jPanelVoyages.add(voyagePanel);
        }
        jPanelVoyages.revalidate();
        jPanelVoyages.repaint();
    }
        // Voyage listesi üzerinden panel+buton oluştur
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Imprint MT Shadow", 0, 30)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TOM Online Reservation");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton8)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(373, 373, 373)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new AdminScreen(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
