/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author HP
 */
import UserModels.*;
import java.awt.*;
import javax.swing.*;
import VoyageModels.Voyage;
import Singleton.VoyageList;
import CompositeFilters.*;
import java.util.ArrayList;
import java.util.List;

public class AllVoyagesScreen extends javax.swing.JFrame {

    /**
     * Creates new form AllVoyagesScreen
     */
    private User currentUser;
    private JPanel jPanelVoyages;
    private VoyageList tripList;
    
    
    public AllVoyagesScreen(User user) {
    initComponents();
    this.currentUser = user;
    tripList = VoyageList.getInstance();

    jPanelVoyages = new JPanel();
    jPanelVoyages.setLayout(new BoxLayout(jPanelVoyages, BoxLayout.Y_AXIS));

    // ScrollPane oluştur
    JScrollPane scrollPane = new JScrollPane(jPanelVoyages);
    scrollPane.setPreferredSize(new Dimension(580, 300));

    // Layout ayarları
// 1️⃣ Üst panel oluştur
    JPanel topPanel = new JPanel();
    topPanel.setLayout(new BoxLayout(topPanel, BoxLayout.Y_AXIS)); // Dikey yerleştir

    // 2️⃣ Başlığı ve filtre panelini içine ekle
    topPanel.add(jLabel5);     // Başlık label
    topPanel.add(filterPanel); // Filtre alanları

    // 3️⃣ Bu üst paneli NORTH'a ekle
    getContentPane().setLayout(new BorderLayout());
    getContentPane().add(topPanel, BorderLayout.NORTH);
    getContentPane().add(scrollPane, BorderLayout.CENTER);


    pack();
    setLocationRelativeTo(null);
    setSize(610, 500);

    // Voyage listesi üzerinden panel+buton oluştur
    for (Voyage trip : tripList) {
        // Her trip için panel
        JPanel voyagePanel = new JPanel(new FlowLayout(FlowLayout.LEFT));

        // Sefer bilgisi label
        JLabel infoLabel = new JLabel(
            trip.getOrigin() + " -> " + trip.getDestination() +
            " | Date: " + trip.getDate() +
            " | Time: " + trip.getTime()
        );

        // Rezervasyon butonu
        JButton reserveButton = new JButton("Make Reservation");
        reserveButton.addActionListener(e -> {
            // 3 seçenekli ekranı aç
            ChooseSeatTypeScreen optionScreen = new ChooseSeatTypeScreen(trip, currentUser);
            optionScreen.setVisible(true);
            this.dispose();
        });

        // Panel içine ekle
        voyagePanel.add(infoLabel);
        voyagePanel.add(reserveButton);

        // Ana panel listesine ekle
        jPanelVoyages.add(voyagePanel);
    }

    // Paneli güncelle
    jPanelVoyages.revalidate();
    jPanelVoyages.repaint();
}

    // Yeni Voyage geldiğinde çağırılacak metod
    public void addTripLabel(Voyage trip) {
        String info = String.format("%s Trip: %s -> %s | %s %s | Code: %s",
            trip.getVoyageType(), trip.getOrigin(), trip.getDestination(),
            trip.getDate(), trip.getTime(), trip.getVoyageCode());

        JLabel label = new JLabel(info);
        label.setBorder(BorderFactory.createEmptyBorder(5,5,5,5));
        jPanelVoyages.add(label);
        jPanelVoyages.revalidate();
        jPanelVoyages.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        filterPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        originField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        destinationField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        filterButton = new javax.swing.JButton();
        clearFilterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Imprint MT Shadow", 0, 30)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("All Voyages");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        filterPanel.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Origin:");

        originField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                originFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Destination:");

        destinationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Date:");

        filterButton.setText("Filter");
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });

        clearFilterButton.setBackground(new java.awt.Color(255, 204, 204));
        clearFilterButton.setText("Clear Filter");
        clearFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFilterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(originField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destinationField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearFilterButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(originField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(destinationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterButton)
                    .addComponent(clearFilterButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(filterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new HomeScreen(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void originFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_originFieldActionPerformed

    private void destinationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationFieldActionPerformed

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
        // TODO add your handling code here:
    // GUI Designer'da eklediğin textfield'lardan veri oku
        String dest = destinationField.getText().trim();
        String origin = originField.getText().trim();
        String date = dateField.getText().trim();

        List<VoyageSpecification> specs = new ArrayList<>();
        if (!dest.isEmpty()) specs.add(new DestinationSpec(dest));
        if (!origin.isEmpty()) specs.add(new OriginSpec(origin));
        if (!date.isEmpty()) specs.add(new DateSpec(date));

        VoyageSpecification finalSpec;
        if (specs.isEmpty()) {
            finalSpec = trip -> true;
        } else if (specs.size() == 1) {
            finalSpec = specs.get(0);
        } else {
            finalSpec = new AndSpec(specs);
        }

        VoyageFilter filter = new VoyageFilter();
        List<Voyage> filtered = filter.filter(tripList, finalSpec);

        // SADECE liste panelini temizle
        jPanelVoyages.removeAll();

        for (Voyage trip : filtered) {
            JPanel voyagePanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
            JLabel infoLabel = new JLabel(
                trip.getOrigin() + " -> " + trip.getDestination() +
                " | Date: " + trip.getDate() +
                " | Time: " + trip.getTime()
            );
            JButton reserveButton = new JButton("Make Reservation");
            reserveButton.addActionListener(e -> {
                ChooseSeatTypeScreen optionScreen = new ChooseSeatTypeScreen(trip, currentUser);
                optionScreen.setVisible(true);
                this.dispose();
            });

            voyagePanel.add(infoLabel);
            voyagePanel.add(reserveButton);
            jPanelVoyages.add(voyagePanel);
        }

        jPanelVoyages.revalidate();
        jPanelVoyages.repaint();
    }//GEN-LAST:event_filterButtonActionPerformed

    private void clearFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFilterButtonActionPerformed
        // TODO add your handling code here:// Textfield'ları temizle
        destinationField.setText("");
        originField.setText("");
        dateField.setText("");

        // Tüm listeyi geri yükle
        VoyageFilter filter = new VoyageFilter();
        List<Voyage> allTrips = filter.filter(tripList, trip -> true); // Tüm seferler

        jPanelVoyages.removeAll();

        for (Voyage trip : allTrips) {
            JPanel voyagePanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
            JLabel infoLabel = new JLabel(
                trip.getOrigin() + " -> " + trip.getDestination() +
                " | Tarih: " + trip.getDate() +
                " | Saat: " + trip.getTime()
            );
            JButton reserveButton = new JButton("Make Reservation");
            reserveButton.addActionListener(e -> {
                ChooseSeatTypeScreen optionScreen = new ChooseSeatTypeScreen(trip, currentUser);
                optionScreen.setVisible(true);
                this.dispose();
            });

            voyagePanel.add(infoLabel);
            voyagePanel.add(reserveButton);
            jPanelVoyages.add(voyagePanel);
        }

        jPanelVoyages.revalidate();
        jPanelVoyages.repaint();

    }//GEN-LAST:event_clearFilterButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearFilterButton;
    private javax.swing.JTextField dateField;
    private javax.swing.JTextField destinationField;
    private javax.swing.JButton filterButton;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField originField;
    // End of variables declaration//GEN-END:variables
}
