/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author HP
 */
import VoyageModels.Voyage;
import UserModels.*;
import javax.swing.*;
import java.awt.*;
import Reservation.ReservationData;

public class MyReservationsScreen extends javax.swing.JFrame {

    /**
     * Creates new form MyReservationsScreen
     */
    private JPanel myReservationsPanel;
    private User currentUser;
    private Reservation.ReservationContext reservationContext;
    
    public MyReservationsScreen(User user) {
        initComponents();
        setLocationRelativeTo(null);
        this.currentUser = user;
        
        myReservationsPanel = new JPanel();
        myReservationsPanel.setLayout(new BoxLayout(myReservationsPanel, BoxLayout.Y_AXIS));
        // Kullanıcının rezervasyonlarını ekrana ekle
        for (ReservationData reservation : currentUser.getReservations()) {
            Voyage trip = reservation.getVoyage();
            int seatNumber = reservation.getSeatNumber();
            String info = String.format("%s -> %s | Date: %s | Time: %s | Seat: %d",
                trip.getOrigin(), trip.getDestination(), trip.getDate(), trip.getTime(), seatNumber);
            
            JButton removeButton = new JButton("Remove Reservation");
            removeButton.addActionListener(e -> {
                int result = JOptionPane.showConfirmDialog(
                this,
                "Are you sure to delete reservation?",
                "Onay",
                JOptionPane.YES_NO_OPTION
                );
                if (result == JOptionPane.YES_OPTION) {
                    currentUser.removeReservation(reservation);
                    JOptionPane.showMessageDialog(this, "Reservation has been removed.");
                    trip.unReserveSeat(seatNumber-1);
                    new HomeScreen(currentUser).setVisible(true);
                    this.dispose();
                }          
            });
            
           
            
            JPanel reservationPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
            JLabel label = new JLabel(info);
            reservationPanel.add(label);
            reservationPanel.add(removeButton);
            myReservationsPanel.add(reservationPanel);
        }
        
        JScrollPane scrollPane = new JScrollPane(myReservationsPanel);
        scrollPane.setPreferredSize(new Dimension(580, 300));
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(jLabel5, BorderLayout.NORTH);
        getContentPane().add(jSeparator1, BorderLayout.AFTER_LAST_LINE);
        getContentPane().add(scrollPane, BorderLayout.CENTER);
        
        pack();
    }
    
    // addReservation metodu artık sadece panel ekler, kullanıcıya eklemez
    public void addReservation(Voyage trip, int seatNumber) {
        JPanel reservationPanel = new JPanel();
        reservationPanel.setLayout(new FlowLayout(FlowLayout.LEFT));
        JLabel label = new JLabel(trip.getOrigin() + " -> " + trip.getDestination() +
                                 " | Date: " + trip.getDate() +
                                 " | Time: " + trip.getTime() +
                                 " | Seat: " + seatNumber);
        reservationPanel.add(label);
        myReservationsPanel.add(reservationPanel);
        myReservationsPanel.revalidate();
        myReservationsPanel.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Imprint MT Shadow", 0, 30)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("My Reservations");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new HomeScreen(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
